/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155__factory>;
    getContractFactory(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataURI__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Receiver__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ERC721A2IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721A2IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC721A2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721A2__factory>;
    getContractFactory(
      name: "ERC721ExtraData",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721ExtraData__factory>;
    getContractFactory(
      name: "FreeClaim",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FreeClaim__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IMoonBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMoonBase__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC721A",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721A__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IMoonLanderzNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMoonLanderzNFT__factory>;
    getContractFactory(
      name: "MoonBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MoonBase__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "MoonLanderzNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MoonLanderzNFT__factory>;
    getContractFactory(
      name: "MoonLanderzNFTBanner",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MoonLanderzNFTBanner__factory>;
    getContractFactory(
      name: "NFTContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NFTContract__factory>;
    getContractFactory(
      name: "NFTContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NFTContract__factory>;
    getContractFactory(
      name: "NFTContractWithExtra",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NFTContractWithExtra__factory>;
    getContractFactory(
      name: "SpaceshipChunk",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SpaceshipChunk__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IMoonLanderzNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMoonLanderzNFT__factory>;
    getContractFactory(
      name: "MoonBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MoonBase__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IMoonLanderzNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMoonLanderzNFT__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "TestMoonBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestMoonBase__factory>;
    getContractFactory(
      name: "TestNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestNFT__factory>;
    getContractFactory(
      name: "TestWithdrawFairly",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestWithdrawFairly__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "WithdrawFairly",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WithdrawFairly__factory>;
    getContractFactory(
      name: "ERC721AIERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721AIERC721Receiver__factory>;
    getContractFactory(
      name: "ERC721A",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721A__factory>;
    getContractFactory(
      name: "ERC721ABurnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721ABurnable__factory>;
    getContractFactory(
      name: "IERC721ABurnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721ABurnable__factory>;
    getContractFactory(
      name: "IERC721A",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721A__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155>;
    getContractAt(
      name: "IERC1155MetadataURI",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataURI>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Receiver>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ERC721A2IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721A2IERC721Receiver>;
    getContractAt(
      name: "ERC721A2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721A2>;
    getContractAt(
      name: "ERC721ExtraData",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721ExtraData>;
    getContractAt(
      name: "FreeClaim",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FreeClaim>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IMoonBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMoonBase>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC721A",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721A>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IMoonLanderzNFT",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMoonLanderzNFT>;
    getContractAt(
      name: "MoonBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MoonBase>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "MoonLanderzNFT",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MoonLanderzNFT>;
    getContractAt(
      name: "MoonLanderzNFTBanner",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MoonLanderzNFTBanner>;
    getContractAt(
      name: "NFTContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.NFTContract>;
    getContractAt(
      name: "NFTContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.NFTContract>;
    getContractAt(
      name: "NFTContractWithExtra",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.NFTContractWithExtra>;
    getContractAt(
      name: "SpaceshipChunk",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SpaceshipChunk>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IMoonLanderzNFT",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMoonLanderzNFT>;
    getContractAt(
      name: "MoonBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MoonBase>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IMoonLanderzNFT",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMoonLanderzNFT>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "TestMoonBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestMoonBase>;
    getContractAt(
      name: "TestNFT",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestNFT>;
    getContractAt(
      name: "TestWithdrawFairly",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestWithdrawFairly>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "WithdrawFairly",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WithdrawFairly>;
    getContractAt(
      name: "ERC721AIERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721AIERC721Receiver>;
    getContractAt(
      name: "ERC721A",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721A>;
    getContractAt(
      name: "ERC721ABurnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721ABurnable>;
    getContractAt(
      name: "IERC721ABurnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721ABurnable>;
    getContractAt(
      name: "IERC721A",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721A>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
