/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface WithdrawFairlyInterface extends utils.Interface {
  contractName: "WithdrawFairly";
  functions: {
    "callers(address)": FunctionFragment;
    "parts(uint256)": FunctionFragment;
    "shareETHRoyaltiesPart()": FunctionFragment;
    "shareTokenRoyaltiesPart(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "callers", values: [string]): string;
  encodeFunctionData(functionFragment: "parts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "shareETHRoyaltiesPart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "shareTokenRoyaltiesPart",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "callers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "parts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shareETHRoyaltiesPart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shareTokenRoyaltiesPart",
    data: BytesLike
  ): Result;

  events: {};
}

export interface WithdrawFairly extends BaseContract {
  contractName: "WithdrawFairly";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WithdrawFairlyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    callers(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    parts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { wallet: string; royaltiesPart: BigNumber }
    >;

    shareETHRoyaltiesPart(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    shareTokenRoyaltiesPart(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  callers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  parts(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber] & { wallet: string; royaltiesPart: BigNumber }
  >;

  shareETHRoyaltiesPart(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  shareTokenRoyaltiesPart(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    callers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    parts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { wallet: string; royaltiesPart: BigNumber }
    >;

    shareETHRoyaltiesPart(overrides?: CallOverrides): Promise<void>;

    shareTokenRoyaltiesPart(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    callers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    parts(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    shareETHRoyaltiesPart(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    shareTokenRoyaltiesPart(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    callers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    shareETHRoyaltiesPart(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    shareTokenRoyaltiesPart(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
